# Application configuration
spring.application.name=e-shop
server.port=8080
server.servlet.context-path=/api/v1
spring.profiles.active=dev
debug=true

# Database configuration
spring.h2.console.enabled=true
# connection protocol:database:in-memory_db:name_of_in-memory_db
spring.datasource.url=jdbc:h2:mem:eshopdb
spring.jpa.show-sql=true
spring.jpa.hibernate.format_sql=true

# DDL auto configuration
#spring.jpa.hibernate.ddl-auto=create-drop (default)
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update
